first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    # ex: /first_app/
    path('', views.index, name='index'),
    # ex: /first_app/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /first_app/5/results/
    path('<int:question_id>/result/', views.result, name='result'),
    # ex: /first_app/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

my_first_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls'), name='first_app'),
]

first_app/models.py
from django.db import models

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

first_app/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from first_app.models import Choice, Question

def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	context = {'latest_question_list': latest_question_list}
	return render(request, 'first_app/index.html', context)

def detail(request, question_id):
	question = get_object_or_404(Question,pk=question_id)
	return render(request, 'first_app/detail.html', {'question' : question})

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		#설문 폼을 다시 보여준다
		return render(request, 'first_app/detail.html', {
			'question' : question,
			'error_message' : "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('first_app:result', args=(question.id,)))

def result(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'first_app/results.html', {'question':question})

first_app/templates/first_app/detail.html
<!DOCTYPE html>
<html>
<head>
<title>{{ question.question_text }}</title>
</head>

<body>
<h1>{{ question.question_text }}</h1><hr/>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'first_app:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
</body>
</html>

first_app/templates/first_app/index.html
<!DOCTYPE html>
<html>
<head>
<title>polls</title>
</head>

<body>
<h1>Questions</h1><hr/>
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'first_app:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}
</body>
</html>

first_app/templates/first_app/results.html
<!DOCTYPE html>
<html>
<head>
<title>vote results</title>
</head>

<body>
<h1>{{ question.question_text }}</h1><hr/>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} - {{ choice.votes }} vote{{choice.votes|pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'first_app:detail' question.id %}">Vote again</a>
</body>
</html>